CREATE TABLE IF NOT EXISTS users_comments
(
    id      INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INT          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    comment VARCHAR(255) NOT NULL
);
